version: "3"

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    environment:
    - TZ=Asia/Shanghai
    ports:
    - 9429:80
    restart: always

# docker-compose -f $PWD/cyberchef.yml up -d
