version: "3"

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9429:80
    restart: unless-stopped
# sudo docker-compose -f /home/server/09-cyberchef/cyberchef.yml up -d
