version: "3"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    - WEBUI_PORT=9422
    - TORRENTING_PORT=9423
    volumes:
    - ./appdata/config:/config
    - /mnt/nas/qbittorrent:/downloads
    ports:
    - 9422:9422
    - 9423:9423
    - 9423:9423/udp
    restart: always

# docker-compose -f $PWD/qbittorrent.yml up -d
