version: "3"

services:
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeserver
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    - PASSWORD=root
    - SUDO_PASSWORD=root
    ports:
    - 9433:8443
    volumes:
    - /home/server/13-codeserver/config:/config
    restart: unless-stopped

# sudo docker-compose -f /home/server/13-codeserver/codeserver.yml up -d
