version: "3"

services:
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    volumes:
    - ./root:/root
    ports:
    - 9420:9876
    restart: always

# docker-compose -f $PWD/ddns-go.yml up -d
