services:
  mihomo:
    image: mihomo:v1
    container_name: mihomo
    # network_mode: host
    ports:
      - "1081:1081"
      - "7894:7894"
    volumes:
      - ./config/mihomo:/root/.config/mihomo
    environment:
      - TZ=Asia/Shanghai
    restart: always
  
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    ports:
      - '7894:7894'
      - '80:80'
    # volumes:
    #   - ./config/webui:/
    environment:
      - TZ=Asia/Shanghai
      - WEB_PASSWORD="admin"
    restart: always

networks:
  default:
    name: mihomo-network