FROM mysql:5.7.44

COPY ./init.sql /docker-entrypoint-initdb.d/

# 允许远程连接并配置端口
RUN echo "[mysqld]" >> /etc/mysql/my.cnf \
    && echo "bind-address = 0.0.0.0" >> /etc/mysql/my.cnf \
    && echo "port = 9447" >> /etc/mysql/my.cnf \
    && echo "sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" >> /etc/mysql/my.cnf
