version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "yourstrongrootpassword"
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/mysql
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    network_mode: "host"
    restart: unless-stopped

# docker build -t mysql .
# docker-compose -f $PWD/mysql.yml up -d
