version: '3'

services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        volumes:
            - /home/server/02-alist/data:/opt/alist/data
            - /home/server/02-alist/storage:/opt/alist/storage
        ports:
            - 9420:5244
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=022
            - TZ=Asia/Shanghai
        restart: always

# sudo docker compose -f /home/server/02-alist/alist.yml up -d
# sudo docker compose -f /home/server/02-alist/alist.yml down
# sudo docker compose -f /home/server/02-alist/alist.yml restart