version: "3"

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=022
    - TZ=Asia/Shanghai
    volumes:
    - /home/server/02-alist/data:/opt/alist/data
    - /home/server/02-alist/nas:/opt/alist/nas
    ports:
    - 9421:5244
    restart: unless-stopped

# sudo docker-compose -p 02-alist -f /home/server/02-alist/alist.yml up -d
