version: "3"

services:
  transfersh:
    image: transfer.sh-1000
    container_name: transfersh
    environment:
    - TZ=Asia/Shanghai
    - TEMP_PATH=/tmp
    - BASEDIR=/home/storage
    - LOG=/home/storage/log
    command: --provider local
    volumes:
    - ./storage:/home/storage
    ports:
    - 9425:8080
    restart: always

# docker-compose -f $PWD/transfersh.yml up -d
