version: "3"

services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    environment:
    - UMASK=022
    - TZ=Asia/Shanghai
    volumes:
    - ./data:/root/.synctv
    ports:
    - 9424:8080
    restart: always

# docker-compose -f $PWD/synctv.yml up -d
