version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    volumes:
    - ./synapse/data:/data
    restart: always

  element:
    image: vectorim/element-web:latest
    container_name: element
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    volumes:
    - ./element/config.json:/app/config.json
    restart: always

  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    restart: always

# docker-compose -f $PWD/matrix.yml up -d
